name: Deploy to OVH

on:
  push:
    branches:
      - main
      - master # In case the main branch is named master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files to OVH
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Si le site n'est pas à la racine du FTP OVH (ex: dans un dossier www), on peut l'indiquer ici :
        # server-dir: /www/
